/*
Notes
https://developers.google.com/apps-script/guides/slides/presentations

https://developers.google.com/apps-script/reference/slides/slides-app

*/
function onOpen() {
  SlidesApp.getUi().createMenu('Math Extension')
      .addItem('Menu', 'showSidebar')
      //.addItem('Refresh Data', 'loadDataToSpreadSheet')
      .addToUi();
   Logger.log("started");
}


function showSidebar() {
  /* old way of doing it
  var html = HtmlService.createHtmlOutputFromFile('Page')
      .setTitle('Fit Sync')
      .setWidth(300);
   */
  var html = doGet().setTitle('Math Solver').setWidth(300);
  SlidesApp.getUi() // Or DocumentApp or FormApp.
      .showSidebar(html);
}

function onInstall(){
  onOpen();
}


function doGet() {
  return HtmlService
      .createTemplateFromFile('index')
      .evaluate();
}

function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename)
      .getContent();
}

function setImage(blob){
  //var blob = "iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAKGUlEQVR4Xu3YsYkVWBzF4TsYWYAYGGwx1mEZtmHoZhtYg9EGFiPYxMLCZgsiGM3w7o/zTQHvnf93LgfmPR1/BAgQiAg8RXKKSYAAgWOw7noE7+6K8/A0Px6eQICrBAzWVXWcD+ecL3dFeliaP8453x/27b74SgGDdVctr+6K8/A0/z48gQBXCRisq+oQhgCB3wkYLO+DAIGMgMHKVCUoAQIGyxsgQCAjYLAyVQlKgIDB8gYIEMgIGKxMVYISIGCwvAECBDICBitTlaAECBgsb4AAgYyAwcpUJSgBAgbLGyBAICNgsDJVCUqAgMHyBggQyAgYrExVghIgYLC8AQIEMgIGK1OVoAQIGCxvgACBjIDBylQlKAECBssbIEAgI2CwMlUJSoDArYP1/pzzST3zAh/POX/PKwD4X+DmwXqtp3mBfwzW/Bv4CeDWwdISAQIEfhEwWB5FReDtOeevc87Xc86fldByPq+AwXpeT5/2cgJvzjmfzznfDNbLId/+yQbr9obkI0Dg+h/dVUSAAAG/YXkDBAh0BfxL2O1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBroDB6nYnOYE5AYM1V7mDCXQFDFa3O8kJzAkYrLnKHUygK2Cwut1JTmBOwGDNVe5gAl0Bg9XtTnICcwIGa65yBxPoChisbneSE5gTMFhzlTuYQFfAYHW7k5zAnIDBmqvcwQS6Agar253kBOYEDNZc5Q4m0BUwWN3uJCcwJ2Cw5ip3MIGugMHqdic5gTkBgzVXuYMJdAUMVrc7yQnMCRisucodTKArYLC63UlOYE7AYM1V7mACXQGD1e1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBroDB6nYnOYE5AYM1V7mDCXQFDFa3O8kJzAkYrLnKHUygK2Cwut1JTmBOwGDNVe5gAl0Bg9XtTnICcwIGa65yBxPoChisbneSE5gTMFhzlTuYQFfAYHW7k5zAnIDBmqvcwQS6Agar253kBOYEDNZc5Q4m0BUwWN3uJCcwJ2Cw5ip3MIGugMHqdic5gTkBgzVXuYMJdAUMVrc7yQnMCRisucodTKArYLC63UlOYE7AYM1V7mACXQGD1e1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBroDB6nYnOYE5AYM1V7mDCXQFDFa3O8kJzAkYrLnKHUygK2Cwut1JTmBOwGDNVe5gAl0Bg9XtTnICcwIGa65yBxPoChisbneSE5gTMFhzlTuYQFfAYHW7k5zAnIDBmqvcwQS6Agar253kBOYEDNZc5Q4m0BUwWN3uJCcwJ2Cw5ip3MIGugMHqdic5gTkBgzVXuYMJdAUMVrc7yQnMCRisucodTKArYLC63UlOYE7AYM1V7mACXQGD1e1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBroDB6nYnOYE5AYM1V7mDCXQFDFa3O8kJzAkYrLnKHUygK2Cwut1JTmBOwGDNVe5gAl0Bg9XtTnICcwIGa65yBxPoChisbneSE5gTMFhzlTuYQFfAYHW7k5zAnIDBmqvcwQS6Agar253kBOYEDNZc5Q4m0BUwWN3uJCcwJ2Cw5ip3MIGugMHqdic5gTkBgzVXuYMJdAUMVrc7yQnMCRisucodTKArYLC63UlOYE7AYM1V7mACXQGD1e1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBroDB6nYnOYE5AYM1V7mDCXQFDFa3O8kJzAkYrLnKHUygK2Cwut1JTmBOwGDNVe5gAl0Bg9XtTnICcwIGa65yBxPoChisbneSE5gTMFhzlTuYQFfAYHW7k5zAnIDBmqvcwQS6Agar253kBOYEDNZc5Q4m0BUwWN3uJCcwJ2Cw5ip3MIGugMHqdic5gTkBgzVXuYMJdAUMVrc7yQnMCRisucodTKArYLC63UlOYE7AYM1V7mACXQGD1e1OcgJzAgZrrnIHE+gKGKxud5ITmBMwWHOVO5hAV8BgdbuTnMCcgMGaq9zBBLoCBqvbneQE5gQM1lzlDibQFTBY3e4kJzAnYLDmKncwga6Awep2JzmBOQGDNVe5gwl0BQxWtzvJCcwJGKy5yh1MoCtgsLrdSU5gTsBgzVXuYAJdAYPV7U5yAnMCBmuucgcT6AoYrG53khOYEzBYc5U7mEBXwGB1u5OcwJyAwZqr3MEEugIGq9ud5ATmBAzWXOUOJtAVMFjd7iQnMCdgsOYqdzCBrsB/MXQNLTk/4s8AAAAASUVORK5CYII="
  var slide = SlidesApp.getActivePresentation().getSlides()[0];
  var imageBlob = Utilities.newBlob(Utilities.base64Decode(blob), MimeType.PNG);
  slide.insertImage(imageBlob);
}